#!/bin/bash
export PYTHONPATH=$(cd "$(dirname "$0")" && pwd):$PYTHONPATH
if [ $# -eq 1 ] && [ "$1" -eq "$1" ] 2>/dev/null
then
   export SLOW_TEST_COVERAGE=$1
else
   export SLOW_TEST_COVERAGE=1
fi
#--------------------------------------------------------------#
# Warning - 100% coverage can take over 30 minutes to complete #
#                                                              #
# Test coverage of < 100% uses random subsets of the specified #
# size for each large resource file.                           #
#--------------------------------------------------------------#
echo Using SLOW_TEST_COVERAGE of $SLOW_TEST_COVERAGE%
pytest test